apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: auth
          image: kodega2016/netapp-auth
          ports:
            - containerPort: 80
              name: auth
        - name: users
          image: kodega2016/netapp-users
          env:
            - name: AUTH_ADDRESS
              value: localhost
          ports:
            - containerPort: 8080
              name: users
---
apiVersion: v1
kind: Service
metadata:
  name: users-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: users
  ports:
    - name: users
      protocol: TCP
      port: 8080
      targetPort: 8080
